### ISSUE TITLE
本科生论文几处与Word模板不符之处

### ISSUE THREAD

**Issue by aichiyu** [CrazyRundong/sht-thesis#1]
使用模板类参数为:
`\documentclass[bachelor, comfort]{shtthesis}`

则有几处与发布的Word模板不符之处:

1. 中文模板「摘要」二字Word模板中间无空格, 而LaTeX模板有. 

2. 英文摘要要求一律用大写字母, 包括「ABSTRACT」自身也是全大写

3. shtthesis-user-guide.pdf文件中, P48「顺序编码制 使用一般引用 \cite 的编码显示为上标，例如...」后的引用并未如介绍那样显示为上标, 而是直接显示为正文, 相应的Word模板中要求显示为上标且为编号数字格式, 与模板不符.

**Comment by lirundong** [comment]
抱歉上个月摸鱼太多，现在才看到...

1. 已在 85736aa 中修复，现不开启 comfort 时「摘要」二字不再包含空格。由于学校不强制对齐 Word 模板，在 comfort 选项开启时仍会保留一个全角空格以提高排版美观度；
2. 已在 85736aa 中修复；
3. 我在 XeLaTeX 和 LuaLaTeX 下均未复现 `\cite` 未上标的情况：

   <img width="568" alt="截屏2021-01-26 上午12 34 56" src="https://user-images.githubusercontent.com/16554459/105736664-03d1f780-5f70-11eb-86f9-e6a7ca233cf1.png">


85736aa 会包含在这周末作的 release v0.3.2 中。

**Comment by lirundong** [comment]
已在 [release v0.3.2](https://github.com/lirundong/shtthesis/releases/tag/v0.3.2) 修复，close this issue.
