### ISSUE TITLE
图片引用~\ref{img::sht_logo}后面需要加一个空格

### ISSUE THREAD

**Issue by fightingnoble** [CrazyRundong/sht-thesis#2]
如题："\~\ref{img::sht_logo}"会显示”??“。"\~\ref{img::sht_logo} "可以成功引用显示图片标号，

**Comment by lirundong** [comment]
Hi @fightingnoble 谢谢反馈，但是我在最新的 [release v0.3.2](https://github.com/lirundong/shtthesis/releases/tag/v0.3.2) 上无法复现你的问题。具体地：

1. 在 [`tree/v0.3.2/shtthesis-user-guide.tex#L733`](https://github.com/lirundong/shtthesis/blob/6d5da5cfdc67d27d54c5f5867d5f0210bed1e9ab/shtthesis-user-guide.tex#L733)，`ref{img::sht_logo}` 后包含一个半角空格：
   ```latex
   《规范》要求正文中所有图形、表格标题使用中英双语。此需求可以通过 \textsf{bicaption} 宏包实现，如图~\ref{img::sht_logo} 所示。
   ```

   此时使用 XeLaTeX 编译可以正确引用图片编号：
  
   <img width="678" alt="截屏2021-03-07 下午10 41 37" src="https://user-images.githubusercontent.com/16554459/110243669-556d9900-7f96-11eb-9229-918d662c8c69.png">
2. 若去除 `ref{img::sht_logo}` 之后的半角空格：
   ```latex
   《规范》要求正文中所有图形、表格标题使用中英双语。此需求可以通过 \textsf{bicaption} 宏包实现，如图~\ref{img::sht_logo}所示。
   ```

   图片编号仍然正确，只是“图 2.1”和“所示”间宽为 `0.5\ccwd` 的间隔消失：
   <img width="698" alt="截屏2021-03-07 下午10 45 15" src="https://user-images.githubusercontent.com/16554459/110243779-d0cf4a80-7f96-11eb-82ae-9c670e604e3b.png">

请尝试清空编译缓存后再次编译：
```bash
$ latexmk -C
$ latexmk -xelatex -outdir=build shtthesis-user-guide.tex
```
若仍然出错，烦请提供您的 `shtthesis-user-guide.tex` 和编译日志 `shtthesis-user-guide.log`。谢谢～

**Comment by lirundong** [comment]
@fightingnoble 若还有问题请附上 log，关闭此 issue
