### ISSUE TITLE
Failed on bibtex

### ISSUE THREAD

**Issue by xuyoji** [CrazyRundong/sht-thesis#3]
Nice work Rundong!
But when I use the default bibtex to compile bib, it said:
` found no \citation commands---while reading file shtthesis-user-guide.aux`
I finally solved it by compiling bib with biber rather than bibtex.

**Comment by lirundong** [comment]
Hey @xuyoji, in the latest v0.3.2 release we're using `biblatex` to typeset bibliography. By default `latexmk` will invoke `biber` to compile it and everything goes fine on my side:
```bash
$ latexmk -xelatex -outdir=build shtthesis-user-guide.tex
# ...
------------
Run number 2 of rule 'biber build/shtthesis-user-guide'
------------
------------
Running 'biber  "build/shtthesis-user-guide.bcf"'
------------
```

Please try to compile with the above command, thanks for your feedback!

**Comment by lirundong** [comment]
No new problem raised. Close this issue.
