### ISSUE TITLE
三级标题未定义

### ISSUE THREAD

**Issue by xuyoji** [CrazyRundong/sht-thesis#4]
润东好：
感谢你为我们呈现的优秀的模板，给我们的毕业论文写作提供了极大的便利。
我在写作中遇到了三级标题(subsubsection)显示异常的情况，如下图所示（红色方框为后期马赛克）：
<img width="137" alt="截屏2022-02-23 下午9 08 06" src="https://user-images.githubusercontent.com/17856220/155325628-8a59a951-7edd-4309-9637-e2b7b97df2eb.png">
经查看.cls文件后，发现其在.cls中未定义，故latex选择了默认参数进行编译。
根据最新的[上海科技大学2022年研究生毕业论文写作规范](http://faculty.sist.shanghaitech.edu.cn/office/Academics/Graduate/Graduate%20Defence/2021SummerDefence/1.ThesisWritingRequirementofShanghaiTech.doc)，三级标题与二级标题一致，故可修改.cls文件，在段落部分添加定义如下：
```
subsubsection = {
    format = \heiti\normalsize\linespread{1.0}\raggedright,
    nameformat = {},
    numberformat = \rmfamily,
    titleformat = {},
    aftername = \hspace{0.75\ccwd},
    beforeskip = {12pt},
   afterskip = {6pt},
 },
```

修改后显示效果如下：
![截屏2022-02-23 下午9 13 27](https://user-images.githubusercontent.com/17856220/155326282-18720e8b-fab7-404c-ac96-bc31bed8a87c.png)

**Comment by lirundong** [comment]
Uhh, good catch! Reproduced:

LaTeX source:
```latex
\subsubsection{三级标题测试}
三级章节段落。
```

Generated PDF:

| v0.3.2 | After modification |
|:------:|:----:|
|<img width="199" alt="截屏2022-02-27 上午12 37 16" src="https://user-images.githubusercontent.com/16554459/155851647-bc5c89b2-4d77-4eaa-b6f1-deec2849e630.png"> | <img width="194" alt="截屏2022-02-27 上午12 40 18" src="https://user-images.githubusercontent.com/16554459/155851649-cd53b452-7e1b-4fdf-a156-fa05a47d7d0d.png"> |

Will push a change soon.

**Comment by lirundong** [comment]
Fixes released in [v0.3.3](https://github.com/lirundong/shtthesis/releases/tag/v0.3.3).
