### ISSUE TITLE
引用的显示顺序问题

### ISSUE THREAD

**Issue by huzechuan** [CrazyRundong/sht-thesis#5]
李同学您好，

请问引用的展示的顺序如何按自己编写的顺序来呢？例如我在正文编写的是：”\citep{yarowsky-ngai-2001-inducing,wang2014cross,hu-etal-2021-risk}“，然而生成的pdf显示如下，顺序变了，是按照作者姓名首字母来排序的。

<img width="265" alt="image" src="https://user-images.githubusercontent.com/46393590/155533531-faa67b7f-cd98-473f-bdda-35d7aa65f36a.png">

**Comment by hushidong** [comment]
加上一个选选项sortcites=false
```
\usepackage[style=gb7714-2015ay,sortcites=false]{biblatex}
```

**Comment by huzechuan** [comment]
> 加上一个选选项sortcites=false
> 
> ```
> \usepackage[style=gb7714-2015ay,sortcites=false]{biblatex}
> ```

谢谢，解决了！

**Comment by lirundong** [comment]
Thank you, @huzechuan for feed back, and @hushidong for a valuable solution! This fix has been released in [v0.3.3](https://github.com/lirundong/shtthesis/releases/tag/v0.3.3). Now the citation order is consistent with source document by default.
