### ISSUE TITLE
Cannot compile with BibTex

### ISSUE THREAD

**Issue by Yangliss** [CrazyRundong/sht-thesis#8]
Hi, @lirundong ,  appreciate your detailed user guide. 
But here is a confusing case in that I cannot find the available solution, could you please take a look?
Compiling the unmodified tex code with XeLaTex generates the output pdf file that has no reference page before the appendix. 
Thus I tried BibTex, however, there are three errors raising:
I found no \citations commands BibTex [line1 column1]
I found no \bibdata commands BibTex [line1 column1]
I found no \bibstyle commands BibTex [line1 column1]

For this case, I've tried to add \bibliography{} in the preamble, or \bibliographystyle{} before \end{document}, or \cite{} in tex, or generate a new .bib file, but none of them worked.
Hope there is an easy way to solve it. Look forward to your reply. Thx a lot!

**Comment by lirundong** [comment]
Thank you, Yangliss, for you interest in this project!

As stated in our changelog [here](https://github.com/lirundong/shtthesis/blob/v0.3/CHANGELOG.md#2020-06-23), we have switched to a more modern bibliography backend `biblatex`, which **does not** support BibTeX.

Instead, if you look into the XeLaTeX log carefully you will notice that it has instructed you to use Biber to generate index info:
```log
Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                shtthesis-user-guide
(biblatex)                and rerun LaTeX afterwards.

)
```

So simly call biber after the first XeLaTex pass can fix your issue:
```bash
$ biber shtthesis-user-guide
INFO - This is Biber 2.18
INFO - Logfile is 'shtthesis-user-guide.blg'
INFO - Reading 'shtthesis-user-guide.bcf'
INFO - Found 9 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex file 'reference.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'reference.bib'
INFO - Overriding locale 'zh__pinyin' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Overriding locale 'zh__pinyin' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Sorting list 'gb7714-2015/global//global/global' of type 'entry' with template 'gb7714-2015' and locale 'zh__pinyin'
INFO - Writing 'shtthesis-user-guide.bbl' with encoding 'UTF-8'
INFO - Output to shtthesis-user-guide.bbl
```

Cheers,
RUndong

**Comment by Yangliss** [comment]
Great. Worked! It's the compiler.
Thanks again! 👍
